### ISSUE TITLE
EPIC: Ability to upsell Coast to Coast Classic to Adventure Pass members

### ISSUE THREAD

**Issue by griebelr** [TridentMarketing/Adventure-Pass#1]
Option to Add Coast to Coast Classic to any Adventure Pass:

- [x] Available for Free Pass activations, FL Sales Exit, Agent over the phone paid, and online paid
- [x] Button to ‘Add Coast to Coast Classic’
- [x] Free Pass activations – button appears on agent-pass-activation page as new button
- [ ] FL Sales Exit – button appears on payment processing page
- [x] Agent over the phone paid – button appears on payment processing page
- [ ] Online Paid – button appears on payment processing page
- [x] For Paid Passes this option is only available for Quarterly or Annual payment terms
- [x] If Monthly payment term is selected, the Add Coast to Coast Classic is not available
- [x] Adds $129 to the fees calculated in the purchase
- [x] One time fee must be paid in full
- [x] This fee cannot be split into recurring payments
- [x] Generate electronic application
- [x] Auto fill customer data into form
- [x] Add fees to form
- [x] Collect customer e-signature on form
- [x] Save application as PDF
- [x] Process payment through Adventure Pass merchant account.
- [x] Process this fee separately as a one-time charge, do not add it to the recurring payment set up
- [x] Send email with application PDF to Accounting for implementation

[300104 CTC App.pdf](https://github.com/griebelr/Adventure-Pass/files/15276024/300104.CTC.App.pdf)
