### ISSUE TITLE
EPIC: AP Cancellations

### ISSUE THREAD

**Issue by griebelr** [TridentMarketing/Adventure-Pass#11]
- [ ] Cancel recurring payment in authorize.net
- [ ] Cancel / deactivate membership in Express
- [ ] Include note in member record with date and request for cancellation
- [ ] Send cancellation confirmation email
- [ ] Create a web page to request a cancellation
