### ISSUE TITLE
EPIC: Apply a custom promo code and discount to AP purchase

### ISSUE THREAD

**Issue by griebelr** [TridentMarketing/Adventure-Pass#15]
### Update the content on the adventurepass.us web site:
- [ ] Change header to say "Camp all year with the exclusive Adventure Pass"
- [ ] Remove the block "INTRODUCTORY OFFER IF YOU ACT NOW"
- [ ] Add a block that says "SAVE UP TO $5000 ON CAMPING THIS YEAR"
- [ ] Change price block to say "Only $599"
- [ ] Remove block that says "reg. $500"
- [ ] Remove the time ticker.
- [ ] Change the call to action button to 'START CAMPING TODAY!'

![Image](https://github.com/TridentMarketing/Adventure-Pass/assets/54040971/18348c28-d1ca-4f8d-bdf1-beed3779503c)

### On **ALL** Paid Pass purchase pages:
- [ ] Remove the automatic Introductory $100 discount and modal.
- [ ] Create an index where custom discounts are created and stored.
- [ ] Each code will have it's own discount dollar amount.
- [ ] Multiple discount codes can have the same discount dollar amount.
- [ ] Allow users to enter a custom discount code on the purchase page below the billing cycle and above the credit card info.
- [ ] Enter code - APPLY
- [ ] Validate the code against the index.
- [ ] Message if code matches active discount: Discount applied successfully.
- [ ] Message if code does not match an active discount or code is inactive: We're sorry, this is not a valid code.
- [ ] Apply the matching custom discount dollar amount based on the code they enter into the invoice section.
- [ ] Maintain rule for Monthly billing cycle - discount is not available. Do not show discount code field if Monthly is selected.

**Comment by griebelr** [comment]
- Redeemed flag set on household
- Active / inactive flag
- Date created
- Track usage - how many times was it redeemed on a sale
- Check discount code text string for dups - cannot have multiple code values
-

**Comment by griebelr** [comment]
Test findings:

- [x] Do not hide the Promo Code field after it is entered and applied. 
- [ ] Users need the ability to remove or change the discount.
- [x] When CTC is added, display the discounted total for Annual Adventure Pass from the top section in the Final Invoice
![Image](https://github.com/user-attachments/assets/992ffcca-217c-414e-b6e7-b85b8b13087b)
- [ ] Update the CTC Application Resort Information section -- can the Total Purchase Price field be dynamic? If not, make the value $599.00 and put this text under the line: *Discounts may apply.
![Image](https://github.com/user-attachments/assets/a88944c7-1bdf-4c03-b05c-679af2a6738c)
- [x] On the quarterly billing cycle, we need to split the discount amount across the 4 payments. Example: If discount amount is $50 then apply $12.50 discount per payment.

**Comment by griebelr** [comment]
- [ ] After the discount code is applied, keep the code displayed in the discount code field
- [ ] Give the user the ability to remove the discount -- add a button beside the Apply button 'Remove Discount'
- [ ] Do not allow the user to use the same discount code more than one time for the same transaction. When I applied the test code again on an open transaction it doubled the discount to $100.
