### ISSUE TITLE
EPIC: Offline mode for AP purchases at shows and events

### ISSUE THREAD

**Issue by griebelr** [TridentMarketing/Adventure-Pass#17]
- [ ] Ability to run a card through a card reader and store transaction detail locally
- [ ] Ability to sync local transaction storage when internet becomes available
- [ ] Handle declined cards and unsettled transactions
- [ ] Text temporary confirmation using cellular service from a device instead of wifi
