### ISSUE TITLE
EPIC: AP Upgrades Flow

### ISSUE THREAD

**Issue by griebelr** [TridentMarketing/Adventure-Pass#20]
- [ ] AP member upgrade eligibility rules
- [ ] Rules engine to push AP members to DLS
- [ ] New reps and schedules for AP member Upgrades

**Comment by maham-nasir** [comment]
AP booking and contract flow:

- [x]  Create a new upgrade booking option in Express (Sohail)
- [x]  Booking flow will be the same with new tag added (Sohail)
- [x]  For bookings, filter out the AP locations by default for UG agents to choose from (Sohail)
- [x]  Location lists for AP (Rosalie)
- [x] Campaign ids for AP (Rosalie)
- [ ]  Selling location of web bookings will be determined by the closest resort/location (Saqib)
- [x]  Create new AP (onsite and online) locations for April to schedule AP UG bookings (Sohail)
- [ ]  If location is onsite, then determine the location by the resort given (Saqib)
- [ ]  If location is web location, then determine location based on their closest resort (Saqib)
- [ ]  In POS, there will be new tab for Adventure pass manifest (Saqib)
- [x] To add this tab, Saqib will need a marker when he receives booking event (Sohail)
- [ ]  In POS, the contract will be defaulted to frontline Trailblazer contract and if they need to add addendum, we should give that option before generating sale contract (Saqib)
- [ ] Need to know which addendums to show for Trailblazer, as the addendums shows in POS depends upon the membership type (Rosalie)
- [ ] Assign new member number at the time of sale based on location (Saqib)
- [ ] Keep the adv pass member number as another key for reference (Sohail)
- [ ] For this particular case, we'll need to add logic to save the new member number from POS, right now the functionality is different(Sohail)
- [ ] Provide a flag on the same level as member number Flag : "isOverrideMemberNumber" (Saqib)
- [x] Add elastic dev for timeslots and locations (Sohail)
- [ ] Reporting on these locations (Rosalie, Hassan)

**Comment by maham-nasir** [comment]
AP upgrades eligibility and DLS mechanism (Rosalie)

**Comment by griebelr** [comment]
@sohail0992 <style type="text/css">td{white-space:normal}br{mso-data-placement:same-cell}</style>
MEMBER | UPGRADE | 66ba07188ed8da1dec68cd60 | Adventure Pass Member Upgrade
-- | -- | -- | --

**Comment by maham-nasir** [comment]
For Upgrade eligibility:
All onsite AP members who are coming to camp (same rule as Onsite bucket) and push them to the TRA onsite list.

**Comment by maham-nasir** [comment]
Any Adventure Pass deal will be loaded under TRICAP with Project code 030 to accommodate the numbering that was started for these deals.  For example, the one financed deal that has been done, Quade, is numbered **300029** - this Equiant account number is **316030002900**.  Please make sure that your coding reflects this properly so that when the accounts are exported, they will be ready to upload into Equiant, without us having to make manual changes. 
-Lyn

**Comment by msohailse** [comment]
# For testing

1. Open this link`https://express-dev.travelresorts.info/?memberno=079737` and click on book now option then select the `Adventure pass` option

<img width="1578" alt="Screenshot 2024-08-27 at 2 05 53 AM" src="https://github.com/user-attachments/assets/f1c3989e-f20d-4987-994d-7044576a2313">

2. Engage will be open with booking view only, please make sure locations only have `AP` locations, fill all the fields and submit the booking
<img width="1135" alt="Screenshot 2024-08-27 at 2 39 53 AM" src="https://github.com/user-attachments/assets/9342166b-e715-402e-8b33-5dd54c611de2">

3. Verification
    - household should have last tag of `66ba07188ed8da1dec68cd60`, 
    - you can also verify it on manifest by turnning on the tag button it should have these values 
    - | MEMBER | UPGRADE | 66ba07188ed8da1dec68cd60 | Adventure Pass Member Upgrade |
