### ISSUE TITLE
EPIC: AP Upgrade Contracts

### ISSUE THREAD

**Issue by griebelr** [TridentMarketing/Adventure-Pass#22]
AP upgrade sales cannot be an addendum because AP members don't have a contract, they only have an agreement.

We will have to create a new contract for AP members to upgrade to full member status.

**Comment by maham-nasir** [comment]
- [ ] Create a new upgrade booking option in Express (Sohail)
- [ ] Booking flow will be the same with new tag added (Sohail)
- [ ] For bookings, filter out the AP locations by default for UG agents to choose from (Sohail)
- [ ] Location lists and campaign ids for AP (Rosalie)
- [ ] Selling location of web bookings will be determined by the closest resort/location  (Saqib)
- [ ] Create new AP (onsite and online) locations for April to schedule AP UG bookings (Sohail)
- [ ] If location is onsite, then determine the location by the resort given (Saqib)
- [ ] If location is web location, then determine location based on their closest resort (Saqib)
- [ ] In POS, there will be new tab for Adventure pass manifest (Saqib)
- [ ] In POS, the contract will be defaulted to frontline Trailblazer contract and if they need to add addendum, we should give that option before generating sale contract (Saqib)
